### ISSUE TITLE
failed to delete description of loopback interface

### ISSUE THREAD

**Issue by dsx1123** [CiscoDevNet/terraform-provider-dcnm#10]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
2021/02/09 16:01:11 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2021/02/09 16:01:11 [INFO] Terraform version: 0.14.6
2021/02/09 16:01:11 [INFO] Go runtime version: go1.15.6
2021/02/09 16:01:11 [INFO] CLI args: []string{"/usr/bin/terraform", "-v"}
2021/02/09 16:01:11 [DEBUG] Attempting to open CLI config file: /home/shdu/.terraformrc
2021/02/09 16:01:11 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021/02/09 16:01:11 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2021/02/09 16:01:11 [DEBUG] ignoring non-existing provider search directory /home/shdu/.terraform.d/plugins
2021/02/09 16:01:11 [DEBUG] ignoring non-existing provider search directory /home/shdu/.local/share/terraform/plugins
2021/02/09 16:01:11 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2021/02/09 16:01:11 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2021/02/09 16:01:11 [INFO] CLI command args: []string{"version", "-v"}
Terraform v0.14.6
+ provider registry.terraform.io/ciscodevnet/dcnm v0.0.1
```

### DCNM version

* V 11.5.1

### Affected Resource(s)

* dcnm_interface

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
terraform {
  required_providers {
    dcnm = {
      source = "CiscoDevNet/dcnm"
      version = "0.0.1"
    }
  }
}
provider "dcnm" {
  username = "admin"
  password = "ins3965!"
  url      = "https://10.20.2.63"
  # expiry   = 900000
}

resource "dcnm_interface" "lo10" {
  fabric_name   = "fabric-dmz"
  name        = "loopback10"
  type        = "loopback"
  policy      = "int_loopback_11_1"

  switch_name_1 = "C9316D-GX-L01"
  ipv4                      = "10.100.100.1"
  vrf                       = "red"
  description               = "creation from terraform"
}
```

### Debug Output

[debug output](https://gist.github.com/dsx1123/e057630a1d26fed67abee61e7381d67d)
### Expected Behavior
description is removed from loopback interface 

### Steps to Reproduce

1. `terraform apply`
2. comment below line:
   `description               = "creation from terraform"`
3. `terraform apply`

### References

* #0000

**Comment by nirav-cloudknox** [comment]
@dsx1123 This is expected behaviour, if you remove any optional parameter after adding it in first operation, Terraform treats the older value till you don't specify the new one. This is done in order to handle the default values set by the the API in case of you don't pass the optional parameters. You can say it's limitation or the way it behaves.

**Comment by nkatarmal-crest** [comment]
@dsx1123 This is accepted behaviour to support the default values in the optional parameters. So if you set it in the first run and remove in the subsequent runs Terraform will not detect it as a change be cause it will think that the API sets the default value for the same.

**Comment by nkatarmal-crest** [comment]
Will remove the computed part, from the description.

**Comment by dsx1123** [comment]
resolved in latest release
