### ISSUE TITLE
Error: Ethernet interface can only be modified

### ISSUE THREAD

**Issue by jomuench** [CiscoDevNet/terraform-provider-dcnm#118]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.3.5
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/dcnm v1.2.7

### DCNM version

* V 12.1.1 (NDFC)

### Affected Resource(s)

* dcnm_interface

### Terraform Configuration Files

```hcl
resource "dcnm_interface" "deploy" {
  name          = "Ethernet1/4"
  type          = "ethernet"
  fabric_name   = var.fabric
  policy        = "int_access_host_11_1"
  switch_name_1 = "Leaf1-gns3"

  bpdu_guard_flag = "true"
  mtu             = "jumbo"
  access_vlans    = dcnm_network.overlay_network.vlan_id
}

```

### Debug Output

Plan: 1 to add, 0 to change, 0 to destroy.
dcnm_interface.deploy: Creating...
╷
│ Error: Ethernet interface can only be modified
│
│   with dcnm_interface.deploy,
│   on port.tf line 1, in resource "dcnm_interface" "deploy":
│    1: resource "dcnm_interface" "deploy" {
│

### Expected Behavior

Ethernet 1/4 to be set to access mode with provided VLAN id.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by RutvikS-crest** [comment]
This is duplicate to #109, Closing this issue. Thanks for reporting !
