### ISSUE TITLE
Terraform import failing for network

### ISSUE THREAD

**Issue by samurato** [CiscoDevNet/terraform-provider-dcnm#119]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v1.0.7

### DCNM version
* V 11.5(2)

### Affected Resource(s)

* dcnm_network

### Terraform Configuration Files

```hcl
resource "dcnm_network" "Auto_Net_VNI141441_VLAN1441" {
}
```

### Debug Output
[Debug Gist](https://gist.github.com/samurato/0e688ad460b958ee28e2b66f8d2d4ee2)

### Panic Output
```
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ImportResourceState call. The plugin logs may contain more details.
```

### Expected Behavior

Should import the existing network and its attachment information

### Actual Behavior
Failing Logs sent above

### Steps to Reproduce

1. `terraform import dcnm_network.Auto_Net_VNI141441_VLAN1441 TEST_FABRIC-SF:P2-I-VNI132883-10_8_212_0m24`

### Important Factoids

Running DCNM in 3 nodes cluster setup with lots of networks pre-existing. Trying to see the feasibility of this module.

### References

* #0000

**Comment by RutvikS-crest** [comment]
Hi @samurato, Can you confirm if you can perform other Terraform operations using same setup?

**Comment by samurato** [comment]
Hi, @RutvikS-crest  looks like it's impacting other terraform operations as well. I tried creating a dummy Network and attaching it to an interface but I am still getting the same error. Any recommendations?

**Comment by RutvikS-crest** [comment]
@samurato, Please check Provider block, I guess it's failing at authentication stage.

**Comment by samurato** [comment]
@RutvikS-crest I checked and reset my passwords. But still having the same problem

**Comment by RutvikS-crest** [comment]
@samurato, Make sure you add `http:// or https://` before host name. I think that should solve your issue, If not do you mind sharing your Provider block without secrets?

**Comment by samurato** [comment]
Hi @RutvikS-crest issue is resolved after adding `https://DCNM_IP`

Many Thanks,
