### ISSUE TITLE
Resource `dcnm_inventory` fails in NDFC 12.1.2e

### ISSUE THREAD

**Issue by jgomezve** [CiscoDevNet/terraform-provider-dcnm#123]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

* V 1.3.8
### DCNM version

* V 12.1.2e

### Affected Resource(s)

* dcnm_inventory

### Terraform Configuration Files

```hcl
resource "dcnm_inventory" "fabric" {
  fabric_name   = "SIMPL-BROWNFIELD"
  username      = "admin"
  password      = "cisco.123"
  max_hops      = 0
  preserve_config = "false"
  auth_protocol = 0
  config_timeout = 15
  switch_config {
    ip   = "1.2.3.4"
    role = "spine"
  }
  switch_config {
    ip   = "5.6.7.8"
    role = "border"
  }
}
```

### Expected Behavior

The switches listed in the resources should be added to the Fabric

### Actual Behavior

Terraform deploy shows `dcnm_inventory.fabric: Still creating...`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

After setting `TF_LOG=DEBUG` it is clear that an API Call to the URL ` GET /appcenter/cisco/ndfc/api/v1/lan-fabricrest/control/fabrics/SIMPL-BROWNFIELD/config-preview HTTP/1.1` failed ( 500 Config Preview is already in progress for the fabric SIMPL-BROWNFIELD. Please try Config Preview later). This produces the following cascading events:

- Method  `prepareSwitchesRoutine` finishes without decrementing the WaiterGroup counter https://github.com/CiscoDevNet/terraform-provider-dcnm/blob/d0ff6c3b92fbe1dfbe1e55e4928a56edf2916879/dcnm/resource_dcnm_inventory.go#L1069 
- Method  `resourceDCNMInventoryCreate` is stuck waiting for the WaitGroup counter to be 0 https://github.com/CiscoDevNet/terraform-provider-dcnm/blob/d0ff6c3b92fbe1dfbe1e55e4928a56edf2916879/dcnm/resource_dcnm_inventory.go#L352

Not sure why this did not happen in a previous version of NDFC/DCNM, since the code tries that call in parallel for all the added devices 

I guess a workaround would be to retry the API call if the content message states `Please try config Preview Later`at this line code https://github.com/CiscoDevNet/terraform-provider-dcnm/blob/d0ff6c3b92fbe1dfbe1e55e4928a56edf2916879/dcnm/resource_dcnm_inventory.go#L854

**Comment by jgomezve** [comment]
The current provider code  waits for the Switch to be in `Normal` mode before assigning the user-defined role. Unfortunately in my current setup (NDFC 12.1.2e + HW N9K) the switches goes first `Normal` for 10 seconds, `Migration` for 2 Minutes and finally back to `Normal`. These state changes produce the Go code to change the device role while the device is still in `Migration` mode. 

According to Engineering this is a exepcted behaviour.  Have the current version of the TF provider  been tested against the latest NDFC versions (12.x) ?

**Comment by dsx1123** [comment]
`dcnm_inventory` doesn't work with browfiled
