### ISSUE TITLE
Issue with dcnm_inventory example 

### ISSUE THREAD

**Issue by trenzy** [CiscoDevNet/terraform-provider-dcnm#19]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is an issue with dcnm_inventory example in both GitHub examples and the Terraform documentation. In the Terraform documentation, the username is listed in the switch config section of the resource (https://registry.terraform.io/providers/CiscoDevNet/dcnm/latest/docs/resources/inventory).

But in the examples on the Github repository (https://github.com/CiscoDevNet/terraform-provider-dcnm/blob/master/examples/inventory/main.tf) it's listed in the configuration of the resource and not in the switch config.

See below for the examples. Which one should it be? Right now, it's confusing.

### New or Affected Resource(s):

* dcnm_inventory

### DCNM version

* V N/A

### Potential Terraform Configuration

```hcl
# Example on Terraform website
resource "dcnm_inventory" "first" {
  fabric_name   = "fab2"
  switch_config {
    username      = "username for DCNM switch"
    password      = "password for DCNM switch"
    ip            = "ip for DCNM switch"
    preserve_config = "false"
    config_timeout = 10
    role = "leaf"
  }
}

# Example from GitHub site:
resource "dcnm_inventory" "first" {
  fabric_name     = "fab2"
  username        = ""
  password        = ""
  preserve_config = "false"
  config_timeout  = 10
  switch_config {
    ip   = ""
    role = "leaf"
  }
}

```

### References

* #0000

**Comment by dsx1123** [comment]
@trenzy the document has been updated. thank you for raising this issue.
