### ISSUE TITLE
destroy failed when destroy multiple resource

### ISSUE THREAD

**Issue by dsx1123** [CiscoDevNet/terraform-provider-dcnm#25]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/dcnm v1.0.0
```

### DCNM version

* V 11.5.2

### Affected Resource(s)

* dcnm_vrf

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
terraform {
  required_providers {
    dcnm = {
      source  = "CiscoDevNet/dcnm"
      version = "1.0.0"
    }
  }
}
provider "dcnm" {
  username = var.dcnm_username
  password = var.dcnm_password
  url      = "https://172.25.74.53"
}

data "dcnm_inventory" "leaf" {
  for_each    = toset(var.leaf)
  fabric_name = var.fabric
  switch_name = each.value
}

resource "dcnm_vrf" "terraform" {
  fabric_name = var.fabric
  name        = "terraform"
  vlan_name   = "terraform"
  deploy      = true
  dynamic "attachments" {
    for_each = [for l in data.dcnm_inventory.leaf : l.serial_number]
    content {
      serial_number = attachments.value
      attach        = true
    }
  }
}

resource "dcnm_network" "terraform" {
  fabric_name  = var.fabric
  name         = "network_terraform"
  description  = "create from terraform"
  vrf_name     = "terraform"
  ipv4_gateway = "10.10.1.1/24"
  ipv6_gateway = "2021:10:10:1::1/64"

  deploy = true
  dynamic "attachments" {
    for_each = [for l in data.dcnm_inventory.leaf : l.serial_number]
    content {
      serial_number = attachments.value
      attach        = true
      switch_ports  = var.int_grp
    }
  }
  depends_on = [
    dcnm_vrf.terraform
  ]
}

```

### Debug Output

[debug output](https://gist.github.com/dsx1123/f5fccd6290a0674a68ab70f27c99b3b4)
### Expected Behavior

vrf and network got deleted from DCNM

### Actual Behavior
network is deleted but vrf is in NA state, it is undeployed from switch but left on DCNM, `terraform destroy` failed with below error:
```
│ Error: 400 Error : "Delete is not allowed as the VRF is under a Deployment operation"
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### References

* #0000

**Comment by gnakh** [comment]
I have the same issue when deleting networks and VRFs. Normally, if you apply the plan again some seconds later, it works.
