### ISSUE TITLE
Terraform created L3 Networks not actually deploying L3 SVIs to switches

### ISSUE THREAD

**Issue by richwats** [CiscoDevNet/terraform-provider-dcnm#55]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

* 1.0.5

### DCNM version

* V 11.5(3)

### Affected Resource(s)

dcnm_network

### Terraform Configuration Files

code is available here:
https://github.com/cisco-apjc-cloud-se/ist-dcn-vcenter

Extracts below...

```json
{
  "dc_fabric": "DC3",
  "dc_networks": {
    "IST-NETWORK-A": {
      "name": "IST-NETWORK-A",
      "description": "Terraform Intersight Demo Network A",
      "ip_subnet": "100.64.63.65/28",
      "vni_id": 32201,
      "vlan_id": 2201,
      "deploy": true
    },
    "IST-NETWORK-B": {
      "name": "IST-NETWORK-B",
      "description": "Terraform Intersight Demo Network B",
      "ip_subnet": "100.64.63.97/28",
      "vni_id": 32202,
      "vlan_id": 2202,
      "deploy": true
    }
  }
}
```

```hcl

## Extract 
resource "dcnm_network" "net" {
  for_each = var.dc_networks

  fabric_name     = var.dc_fabric
  name            = each.value.name
  network_id      = each.value.vni_id
  display_name    = each.value.name
  description     = each.value.description
  vrf_name        = data.dcnm_vrf.dc_vrf.name
  vlan_id         = each.value.vlan_id
  vlan_name       = each.value.name
  ipv4_gateway    = each.value.ip_subnet
  # ipv6_gateway    = "2001:db8::1/64"
  # l2_only_flag    = false
  # mtu             = 1500
  # secondary_gw_1  = "192.0.3.1/24"
  # secondary_gw_2  = "192.0.3.1/24"
  # arp_supp_flag   = true
  # ir_enable_flag  = false
  # mcast_group     = "239.1.2.2"
  # dhcp_1          = "1.2.3.4"
  # dhcp_2          = "1.2.3.5"
  # dhcp_vrf        = "VRF1012"
  # loopback_id     = 100
  # tag             = "1400"
  # rt_both_flag    = true
  # trm_enable_flag = true
  l3_gateway_flag = true
  deploy          = each.value.deploy

  dynamic "attachments" {
    # for_each = each.value.attachments
    for_each = local.merged
    content {
      serial_number = attachments.value["serial_number"]
      vlan_id = each.value.vlan_id
      attach = attachments.value["attach"]
      switch_ports = attachments.value["switch_ports"]
    }
  }

  depends_on = [dcnm_interface.vpc]
}
```

### Expected Behavior

We should see an L3 SVI (i.e. interface vlan 2201) with the IPv4 address in the correct VRF deployed as a configuration profile to the target switches.

### Actual Behavior

In the DCNM GUI, the Network looks correct.  It shows the correct VLAN & IPv4 gateway details.  However when I look the resulting DCNM policy instance, there is no L3 SVI defined - it is as if the Network has the L2 Only flag set, but it doesn't.
 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Can be demo'd internally 

### References

* #0000

**Comment by lhercot** [comment]
This issue is fixed in v1.1.0. Thanks for opening the issue and feel free to open new issues you find.
