### ISSUE TITLE
Create Network isn't Creating SVI

### ISSUE THREAD

**Issue by malriddell** [CiscoDevNet/terraform-provider-dcnm#58]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

% terraform -v
Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/ciscodevnet/dcnm v1.0.0

### DCNM version

* V 11.5(1)
### Affected Resource(s)

* dcnm_network

### Terraform Configuration Files
% cat 3_build_net.tf 

resource "dcnm_network" "first" {
  fabric_name     = var.user.fabric_name
  name            = var.user.lan1_name
  network_id      = var.user.lan1_vni
  display_name    = var.user.lan1_name
  description     = "First Network Terraform"
  vrf_name        = var.user.vrf1_name
  vlan_id         = var.user.lan1_vlan
  vlan_name       = "Network_1"
  ipv4_gateway    = var.user.lan1_gw
  mtu             = 9216
  arp_supp_flag   = false
  ir_enable_flag  = false
  rt_both_flag    = true
  trm_enable_flag = false
  l3_gateway_flag = true
  deploy = true
  attachments {
    attach = true
    serial_number = var.user.bl1_sn
  }
  attachments {
    attach = true
    serial_number = var.user.bl2_sn
  }
  attachments {
    attach = true
    serial_number = var.user.lf1_sn
  }
  attachments {
    attach = true
    serial_number = var.user.lf3_sn
  }
  attachments {
    attach = true
    serial_number = var.user.lf2_sn
  }
}

% cat variable.tf 
variable "user" {
  description = "Login information"
  type        = map
  default     = {
    username = "****"
    password = "****"
    url      = "https://****"
    fabric_name = "VXLAN_Site_C"
    lf1_sn   = "9SU6BEXPIZK"
    lf2_sn   = "9GBEBFJD18J"
    lf3_sn   = "9VYR8U7G1RN"
    sp1_sn   = "94GLF7JX1VJ"
    sp2_sn   = "9N4K4VZ8GLR"
    bl1_sn   = "96P2YKIXMPH"
    bl2_sn   = "9F8AN5FTM9F"
    lf1_name = "fab-c-leaf1"
    lf2_name = "fab-c-leaf2"
    lf3_name = "fab-c-leaf3"
    sp1_name = "fab-c-spine1"
    sp2_name = "fab-c-spine2"
    bl1_name = "fab-c-bl1"
    bl2_name = "fab-c-bl2"
    vrf1_name = "cust_a"
    vrf1_vni = "500001"
    vrf1_vlan = "2001"
    vrf2_name = "cust_b"
    vrf2_vni = "500002"
    vrf2_vlan = "2002"
    lan1_name = "Net_101"
    lan1_vni = "30001"
    lan1_vlan = "101"
    lan1_gw = "192.168.1.1/24"
    lan2_name = "Net_102"
    lan2_vni = "30002"
    lan2_vlan = "102"
    lan2_gw = "192.168.2.1/24"
  }
}

### Expected Behavior

Create a L2 Network in DCNM and pushes all the necessary configs to the N9K switches

### Actual Behavior

It actually pushes all the config except the SVI to the switch

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Running terraform on a Macbook Pro.

I can work around the issue by logging into DCNM UI, clicking "Edit/Save" on the network without updating any field.  Then I can hit deploy and it pushes the SVI config to the switch.  It essentially populates DCNM with the information but somehow it doesn't get pushed to the switches.

**Comment by dsx1123** [comment]
@malriddell it will be fixed on next release.
