### ISSUE TITLE
Free_form_config fails due to typo as "free_from_config" instead

### ISSUE THREAD

**Issue by mipetrin** [CiscoDevNet/terraform-provider-dcnm#89]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.2.3
on darwin_amd64
+ provider registry.terraform.io/ciscodevnet/dcnm v1.2.2

### DCNM version

* NDFC 12.0.2f

### Affected Resource(s)

* dcnm_network

### Expected Behavior

Should be able to call upon 

[attachments.free_form_config](https://registry.terraform.io/providers/CiscoDevNet/dcnm/latest/docs/resources/network#attachments.free_form_config) - (Optional) free form configuration for the switch attachment.

### Actual Behavior

This option fails due to a typo in the dcnm_network.go file, incorrectly expects "free_from_config" instead of correct "free_form_config"

* #0000

**Comment by lhercot** [comment]
We merged a fix and it will be available in the next release.
